### ISSUE TITLE
Add deployer to Symfony projects

### ISSUE THREAD

**Issue by peterkokot** [deployphp/deployer.org#1]
Hello, it doesn't concern the deployer.org site directly but I'm opening this issue here anyway for your consideration to check it out. Deployer is definitely interesting tool worth mentioning also on the symfony.com/projects site. I think it would be best from one of maintainers to send pull request there:
https://github.com/symfony/symfony-marketing
instead of outsiders like me :)
What do you think?

**Comment by elfet** [comment]
Yes, will do it, when Deployer 3 will released.

**Comment by peterkokot** [comment]
Ok, thank you very much. That sounds great than. I'll close this ticket. :+1:
