### ISSUE TITLE
Show the current phar's version (3.x), and add the 2.x version too

### ISSUE THREAD

**Issue by ZeeCoder** [deployphp/deployer.org#10]
The site should provide the latest 2.x version of deployer, so that if someone really wants to stick with that, it wouldn't be a problem.
Also it needs to be emphasized, that the current downloaded phar is the 3.x version.

Now if I try to deploy an older application, and I'm not careful enough, I might not even realise that a new major version was added.

Due to this, I won't be able to quickly deploy until:
 - I realise that the new phar is the v3 version,
 - Either I update my deployment tasks - which I might not have time to do -, or I clone the 2.x branch, and build the phar myself.

Both solutions are time-consuming when you're not sure how to do these things.

**Comment by elfet** [comment]
Yes, good point. I think we need to create page for 2.x with available to download old version.
All available download a listed here: http://deployer.org/manifest.json

**Comment by ZeeCoder** [comment]
Wow, that's great.
I have an idea: the "Download deployer.phar" button should include the version number, like "Download deployer.phar (v3.0.3)" and under that there should be a link "Download a different version".

That would redirect to a page, where all - or a subset - of the versions in that manifest.json would be listed.

**Comment by elfet** [comment]
Good solution!

**Comment by elfet** [comment]
But i think it's better to show only latest stable of 3.x and 2.x, and one for beta of 3.x.
I'm planning to hold only 3 latest release on server.

**Comment by ZeeCoder** [comment]
I think that if someone is smart enough to know exactly what version he needs, he should be allowed to choose.

Imagine the following: I'm using version "2.0.0", which includes a bug.
But since I couldn't wait, I wrote a hack, which nicely solves the problem.

Now half a year later, I'm searching for that specific version, but the closest I find is "2.4.6" which introduced a myriad of changes I don't need and which are breaking my hacks all over the place.

Even if "2.0.0" had errors, for my specific case it was perfect, and for that project, I would want to use that if I have no time to upgrade.

I think the site should list everything, but it could highlight the latest major stable releases and betas.

So a list could be something like this:

- 3.4.2-beta
- **3.4.1**
- 3.4.0
- 3.3.6
- ...
- **2.5.6**
- 2.5.6-beta2
- 2.5.6-beta
- 2.5.5
- ...

**Comment by elfet** [comment]
I think you right. 
Can you create this page as PR? If you have any questiong about structure of deployer.org  - feel free to ask.

**Comment by ZeeCoder** [comment]
I need apache configuration to my virtual host settings.
Sharing yours would help a lot. :)

**Comment by ZeeCoder** [comment]
nvm, I solved it.
