### ISSUE TITLE
We should indicate in some way, which feature was introduced in which version

### ISSUE THREAD

**Issue by ZeeCoder** [deployphp/deployer.org#24]
Take the Symfony site's solution as an example.
You can switch back-and-forth between the versions, and see different documentations for them.

Even if we don't want to implement such a "big" feature, we could still indicate in which Deployer version a particular feature is available in.

**Comment by gordalina** [comment]
We could use two files, UPGRADE and CHANGELOG like [symfony](https://github.com/symfony/symfony) does. This makes it simple for people upgrading their deploy scripts.

**Comment by ZeeCoder** [comment]
That's a good idea too.
Apart from that, I was talking about the site's documentations.
For example: there's no indication when the SF3 dir structure got support on the site.
Of course, it can be found in the [release notes](https://github.com/deployphp/deployer/releases), but it would be way nicer, if there were a note in the documentation, like:
"Switching to the Symfony3 dir structure (>=v3.0.1):"

**Comment by gordalina** [comment]
@ZeeCoder i agree that these must be in the documentation, and can be easily parsed into the docs (to prevent rework).
Regarding the symfony3 dir structure, i'm not really sure why they haven't documented it properly.

**Comment by gordalina** [comment]
Btw, I've opened an issue #358 to deal with this, your comments are very welcome :smile:

**Comment by ZeeCoder** [comment]
:+1:

**Comment by ZeeCoder** [comment]
I'm closing this in favour of https://github.com/deployphp/deployer/issues/358.
(Even though that's closed already, I don't think this issue will be solved in the near future anyway.)
