### ISSUE TITLE
Compressing the images

### ISSUE THREAD

**Issue by daskepon** [deployphp/deployer.org#32]
Hi.

I checked this site by with [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fdeployer.org%2F&tab=desktop). 

I think that it would be better to compress the images ( for example https://deployer.org/images/logos/composer.png ) for speed up page speed.

**Comment by antonmedv** [comment]
Agree.

**Comment by daskepon** [comment]
Thank you for PR #34 check & merge.

I close this issue.
