### ISSUE TITLE
Updating web front end build tools and script

### ISSUE THREAD

**Issue by daskepon** [deployphp/deployer.org#33]
Hi.

I' am a user of deployer.

I think that it would be better to update web front end build tools and script because of security, performance quarity.

- gulp
- webpack
- etc...

**Comment by antonmedv** [comment]
I'm thinking to completely rewrite deployer.org to laravel.

**Comment by daskepon** [comment]
If it is better to fix this issue.
I would like to challenge.

Please define version of Node.js and npm. 
I think the following is good.

- Node.js : 8.x ( [current LTS mager version](https://nodejs.org/) )
- npm : 6.x ( [latest version](https://www.npmjs.com/package/npm) )

**Comment by daskepon** [comment]
OK. I will close this issue. 
Thank you !
