### ISSUE TITLE
Deployer.org is offline

### ISSUE THREAD

**Issue by jeancsil** [deployphp/deployer.org#5]
Just to let you known that [www.deployer.org] (http://deployer.org) website is offline for more than 5 days.

**Comment by elfet** [comment]
http://deployer.org is online now. =)

**Comment by jeancsil** [comment]
Hey elfet! The server has gone away again :(

I don't have a webserver to help you with this..
Maybe we can use a github page for this?

See you.

**Comment by elfet** [comment]
Fixed!
