### ISSUE TITLE
Tit ?

### ISSUE THREAD

**Issue by Ham3D** [deployphp/deployer.org#6]
Why the f when you click the green circle Tits show up ?

**Comment by elfet** [comment]
It's a [easter egg](http://en.wikipedia.org/wiki/Easter_egg_(media)).

**Comment by elfet** [comment]
Well, i remove tit from site. Are you happy?

**Comment by Ham3D** [comment]
no offence man,  i wasn't unhappy,  I just saw it not proper.  sorry if
insulted you on anything.
